### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brylie** [sp33dy/Godot-v3-Tutorials-Competent#1]
Under which license are these tutorial projects released? Please add a LICENSE file to the root of this repository, so people know if/how they are allowed to reuse, share, and/or build upon this work. Thanks 😀

**Comment by sp33dy** [comment]
Actioned. MIT licenses, much like Godot is. I've added Licenses. PLEASE NOTE though, please look for any additional licenses for images, i.e. for Space Invaders clone, the images came from FreeGameArt and they have their own stipulation.
